### PR TITLE
Added option to skip parsing of results

### PR DESCRIPTION
**Pull request by forest**

### CODE REVIEW

**Review by sarahdasko — APPROVED** [review]
looks great

i know `update` and `delete` would be duplicates of `insert` but if we're defining one, should we create all? or have a singular more generic on called `ddl_dml`?

**Comment by forest** [comment]
I thought about `update` and `delete` too. Maybe it is best to mimic the `Ecto.Repo` query and schema apis. https://hexdocs.pm/ecto/Ecto.Repo.html#query-api

Those higher-level functions provide some guidance, but user can always drop down to `query` to keep full control.

**Comment by forest** [comment]
Maybe it is actually best to keep the API as is. Just `query` and document when to use the `parse_results` option. I think that is best.

**Review by sarahdasko — APPROVED** [review]
i like it, super simple and allows for us to not pay the transaction and parsing cost

**Pull request merged**
